name: main

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Update rustup
        run: rustup update

      - name: cargo test
        run: cargo test
