name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Update rustup
        run: rustup update

      - name: cargo test
        run: cargo test

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy -- -D warnings
